DROP TABLE IF EXISTS covid_data_220922 CASCADE;
CREATE TABLE covid_data_220922 (
    iso_code text,
    continent text,
    location text,
    date date,
    total_cases numeric,
    new_cases numeric,
    new_cases_smoothed float,
    total_deaths numeric,
    new_deaths numeric,
    new_deaths_smoothed float,
    total_cases_per_million float,
    new_cases_per_million float,
    new_cases_smoothed_per_million float,
    total_deaths_per_million float,
    new_deaths_per_million float,
    new_deaths_smoothed_per_million float,
    reproduction_rate float,
    icu_patients numeric,
    icu_patients_per_million float,
    hosp_patients numeric,
    hosp_patients_per_million float,
    weekly_icu_admissions float,
    weekly_icu_admissions_per_million float,
    weekly_hosp_admissions float,
    weekly_hosp_admissions_per_million float,
    new_tests numeric,
    total_tests numeric,
    total_tests_per_thousand float,
    new_tests_per_thousand float,
    new_tests_smoothed numeric,
    new_tests_smoothed_per_thousand float,
    positive_rate float,
    tests_per_case float,
    tests_units text,
    total_vaccinations numeric,
    people_vaccinated numeric,
    people_fully_vaccinated numeric,
    total_boosters numeric,
    new_vaccinations numeric,
    new_vaccinations_smoothed numeric,
    total_vaccinations_per_hundred float,
    people_vaccinated_per_hundred float,
    people_fully_vaccinated_per_hundred float,
    total_boosters_per_hundred float,
    new_vaccinations_smoothed_per_million float,
    new_people_vaccinated_smoothed numeric,
    new_people_vaccinated_smoothed_per_hundred float,
    stringency_index float,
    population numeric,
    population_density float,
    median_age float,
    aged_65_older float,
    aged_70_older float,
    gdp_per_capita float,
    extreme_poverty float,
    cardiovasc_death_rate float,
    diabetes_prevalence float,
    female_smokers float,
    male_smokers float,
    handwashing_facilities float,
    hospital_beds_per_thousand float,
    life_expectancy float,
    human_development_index float
);

-- copy data from excel
COPY public.covid_data_220922 FROM 'C:\Users\muham\Downloads\DA\2 Porto SQL - COVID Data Exploration 2\covid_data_updated.csv' WITH CSV HEADER;

SELECT * FROM public.covid_data_220922;